# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-07-21 06:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0002_auto_20160721_0318'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='spark_job_id',
            field=models.IntegerField(default=-1),
        ),
    ]
