# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-07-21 06:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0003_job_spark_job_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='spark_job_id',
            field=models.CharField(max_length=100),
        ),
    ]
