# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-07-22 03:24
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0005_auto_20160722_1106'),
    ]

    operations = [
        migrations.RenameField(
            model_name='job',
            old_name='files',
            new_name='code_files',
        ),
    ]
